version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  python-script:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: my_db
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - .:/app

volumes:
  postgres_data: