name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest allure-pytest
        
    - name: Run tests with Allure
      run: |
        python -m pytest tests/ -v --alluredir=allure-results
        
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        retention-days: 30
        
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report
        retention-days: 30

    - name: Verify project structure
      run: |
        echo "Project structure check:"
        ls -la
        echo "---"
        ls -la app/
        echo "---"
        [ -f "Dockerfile" ] && echo "✅ Dockerfile exists" || echo "❌ Dockerfile not found"
        [ -f "docker-compose.yml" ] && echo "✅ docker-compose.yml exists" || echo "❌ docker-compose.yml not found"
        [ -f "requirements.txt" ] && echo "✅ requirements.txt exists" || echo "❌ requirements.txt not found"
        
    - name: Test Docker build
      run: |
        docker build -t my-python-script:ci-test .